name: Go

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ./blockchain-api
        run: |
          go install -v ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Install goveralls
        working-directory: ./blockchain-api
        run: go install github.com/mattn/goveralls@latest

      - name: Build
        working-directory: ./blockchain-api
        run: go build -v ./cmd/...

      - name: Test
        working-directory: ./blockchain-api
        run: |
          go test -v -timeout=60s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mock_" > $GITHUB_WORKSPACE/profile.cov
